language: ruby
git:
  depth: false
cache: bundler
before_install:
- bundle install
after_success:
- script/tag_on_master
script: bundle exec rake book:build
env:
  secure: "O+YCTDgLfCYAJjjOv2sApDRV5NJe6pkhiYIkORFuf2flO8HE72fEtDRpSWh1vulnIH6AjRK2jH7C8qA3MVbUO8D0io+Ha+vnbMXIp1JPCptcJNEkJrW13VTR66SWOzsgLp3mCrIC+YdE2JoYWGcnDsRMQwdnrWnxBzSOd22ZKzU="

before_deploy: bundle install && bundle exec rake book:build
deploy:
  provider: releases
  file:
  - progit.epub
  - progit.mobi
  - progit.pdf
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: "gTe9N46cytofmVkRYcBxzpdh26E4OA3p614LK51MfGVMvBvn/0Ou2j5Pxl8Sr0g24i7HgOhfCNo+uDhkwBz2wkmjuNRsx2OZrCck4V1n4MjXplVvZzmaXB5JRVVtpTd7iwdD6uFfU8MZKUKTACLDYtVQwvCa0r7IuyNFcvLNR325Q5+8N1WxzsQs7M0m+xZ2wfL0tN82B/fFFMv5crYSyJqrKGgPt+Kf3w6yrrFKvD/E0TbO8N1pGcrcMm7fMFRRUB3lVir5BuPYyrjh8X3zuh99/6H9dhtZbB3Qe+OhgzzO+c4JPRHAKnYvpndiDFfs5C3Cyv8ISdXrHv+cEEIrEK/XeGloeMxUCZjRAa/C4F7MydAISwNGOchPtJn1Q38/GVQlmRXYUQ1KBnfP+I1dMvL2Wnyt77RFNRFoTidbOM+cK6Q5wYqgKlEF1d955pgM7Yx0N/4DQUyUVzc2eQdoYd76HHDJnLXf449fR+Q2Eq8vX6l+330hKFN5IRskSliVfvMuETlb9lgt/j8W41f9KYgbZWMsg5EMhxbAyyRyp6afofs1AfIDvXX6pkZ9JAuKx0i095KDP5bS2EYcx5s7DCTeqC978s+Lp26EEX2Bouavcj2/sW/hLuttFDDnAo576Esg3Qs2jQu3K5mrY0PnX/iu/8WRpjdn8DZwCuJrEo0="
branches:
  only:
  - master
  - /^2\.1(\.\d+)+$/

notifications:
  email:
    on_success: never
    on_failure: always
